server:
  port: 18080
spring:
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:tethys-group}
      auto-offset-reset: ${KAFKA_AUTO_OFFSET_RESET:earliest}