apiVersion: v1
kind: Service
metadata:
  name: tethys-service
  labels:
    app: tethys
spec:
  selector:
    app: tethys
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP  # Change to LoadBalancer or NodePort if external access is needed